name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run one-line script
        run: echo "Hello world!"

      - name: Multi-line script
        run: |
          echo "Add other actions"
          echo "to build and test your project"
